build:
	docker build -t aviralgoel/oopsla-2021-r-promisebreaker:latest .

run:
	docker run --cpus 8 --rm -p 8000:8080 -ti aviralgoel/oopsla-2021-r-promisebreaker:latest --name oopsla-2020-r-promisebreaker

push:
	docker push aviralgoel/oopsla-2021-r-promisebreaker:latest

pull:
	docker pull aviralgoel/oopsla-2021-r-promisebreaker:latest
